name: Post JSON File to Two URLs
on:
  push:
    branches:
      - main # Runs only when pushing to the main branch
  workflow_dispatch: # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check JSON File
        run: |
          if [ ! -f stream.json ]; then
            echo "stream.json not found!"
            exit 1
          fi

      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:_VGRgICeT3Cdj8Y3LcJkJQ@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:OfvPhja-Rl-EE5YwwnVfGQ/streams/AQAAALpVcWoSy0KMnbxGQYyoJ6oAAAAA" \
          -H "Content-Type: application/json" \
          -d @stream.json

      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:e1pe4eaEQUuqAsSenosiZQ@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:OfvPhja-Rl-EE5YwwnVfGQ/streams/AQAAAFZaghJOhk21i2co_QZUIQIAAAAA" \
          -H "Content-Type: application/json" \
          -d @stream.json
